<a href="https://colab.research.google.com/github/Raquib603/Google-Colab-Notebook/blob/main/Drop_column.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/world_population.csv')
df.tail(5)

In [ ]:
df.set_index('Rank', inplace = True)
df

In [ ]:
df.sort_index(ascending = True, inplace = True)
df.head(6)

In [22]:
#0 means that we are selecting rows, 1 means that we are selecting columns
df.drop('Capital', axis= 1, inplace = True)
df

,CCA3,Country,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Rank,,,,,,,,,,,,,,,
1,CHN,China,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
2,IND,India,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
3,USA,United States,North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
4,IDN,Indonesia,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
5,PAK,Pakistan,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,MSR,Montserrat,North America,4.390000e+03,4.500000e+03,5.059000e+03,4.938000e+03,5.138000e+03,1.080500e+04,11452.0,11402.0,102.0,43.0392,0.9939,0.00
231,FLK,Falkland Islands,South America,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
232,NIU,Niue,Oceania,1.934000e+03,1.942000e+03,1.847000e+03,1.812000e+03,2.074000e+03,2.533000e+03,3637.0,5185.0,260.0,7.4385,0.9985,0.00
233,TKL,Tokelau,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
234,VAT,Vatican City,Europe,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,733.0,752.0,1.0,510.0000,0.9980,0.00