<a href="https://colab.research.google.com/github/Raquib603/Google-Colab-Notebook/blob/main/basic_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/bike_share_yr_1.csv')
#dataframe is simply rows and columns in the data
#same for the excel files
df.head(10)

In [ ]:
#delete the headers
#set new names to headers : header = none, names = ['a', 'b', 'c']
df = pd.read_csv('/content/bike_share_yr_1.csv', header = None)
df.head()

In [ ]:
df.shape
df.info()

In [29]:
pd.set_option('display.max.rows',200)
pd.set_option('display.max.columns',20)

In [31]:
#to show the last values
df.tail(10)

,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,rider_type,riders
17458,31/12/2022,1,1,12,14,0,1,1,2,0.28,0.2727,0.45,0.2239,registered,185
17459,31/12/2022,1,1,12,15,0,1,1,2,0.28,0.2879,0.45,0.1343,registered,246
17460,31/12/2022,1,1,12,16,0,1,1,2,0.26,0.2576,0.48,0.1940,registered,184
17461,31/12/2022,1,1,12,17,0,1,1,2,0.26,0.2879,0.48,0.0896,registered,150
17462,31/12/2022,1,1,12,18,0,1,1,2,0.26,0.2727,0.48,0.1343,registered,112
17463,31/12/2022,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,registered,108
17464,31/12/2022,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,registered,81
17465,31/12/2022,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,registered,83
17466,31/12/2022,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,registered,48
17467,31/12/2022,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,registered,37

In [ ]:
#to see the specific row`
df.loc[17466]

In [34]:
#to see the columns
df.columns

Index(['dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'rider_type', 'riders'],
      dtype='object')